### ISSUE TITLE
Support for markdown

### ISSUE THREAD

**Issue by woutermont** [kainino0x/vscode-bikeshed#1]
The [Bikeshed spec](https://speced.github.io/bikeshed) [specifies it supports](https://speced.github.io/bikeshed/#markdown) [regular CommonMark](https://commonmark.org), but the VSCode extension does not seem to provide syntax highlighting for it. Since most spec can be written in plain markdown, this makes for a hard decision on whether to use the extension, or stick with good markdown highlighting.

Can you confirm that I am not missing something obvious? If not, how hard would it be to incorporate CommonMark support in the extension?

Thanks!

**Comment by kainino0x** [comment]
TBH I have no idea! I copied this from somewhere else, presumably https://github.com/speced/bikeshed/blob/main/Bikeshed.tmLanguage (weird I didn't document it).
I don't really know how it works or how to edit it.
I'll do a quick update of the syntax file in here for now. Any contributions to the syntax file should be made upstream in Bikeshed :)

**Comment by kainino0x** [comment]
Done. Will close this since any improvements will need to be upstream in Bikeshed.
